name: Deploy tovuti kwa GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Pakua msimbo
        uses: actions/checkout@v4
      - name: Sanidi Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true
      - name: Pakia ukurasa
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - name: Chapisha
        id: deployment
        uses: actions/deploy-pages@v4
